# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'test-artifactory'
- task: Maven@3
  inputs:
    mavenPomFile: 'Application/pom.xml'
    mavenOptions: '-Xmx3072m -Dmaven.test.skip=true'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    goals: 'deploy'
    mavenAuthenticateFeed: true
